---

ignore-failures:

    python:
        - async-generator
        - async-timeout
        - cycler
        - entrypoints
        - ipython-genutils
        - jupyter
        - jupyter-contrib-core
        - jupyter-contrib-nbextensions
        - jupyter-highlight-selected-word
        - jupyter-latex-envs
        - jupyter-nbextensions-configurator
        - markupsafe
        - mistune
        - patsy
        - pickleshare
        - pylev
        - qtpy
        - send2trash
        - testpath
        - webencodings
